package main

func init() {
	chars["02600"] = [][2]string{
		{"Black Sun With Rays", "\u2600"},
		{"Cloud", "\u2601"},
		{"Umbrella", "\u2602"},
		{"Snowman", "\u2603"},
		{"Comet", "\u2604"},
		{"Black Star", "\u2605"},
		{"White Star", "\u2606"},
		{"Lightning", "\u2607"},
		{"Thunderstorm", "\u2608"},
		{"Sun", "\u2609"},
		{"Ascending Node", "\u260a"},
		{"Descending Node", "\u260b"},
		{"Conjunction", "\u260c"},
		{"Opposition", "\u260d"},
		{"Black Telephone", "\u260e"},
		{"White Telephone", "\u260f"},
		{"Ballot Box", "\u2610"},
		{"Ballot Box With Check", "\u2611"},
		{"Ballot Box With X", "\u2612"},
		{"Saltire", "\u2613"},
		{"Umbrella With Rain Drops", "\u2614"},
		{"Hot Beverage", "\u2615"},
		{"White Shogi Piece", "\u2616"},
		{"Black Shogi Piece", "\u2617"},
		{"Shamrock", "\u2618"},
		{"Reversed Rotated Floral Heart Bullet", "\u2619"},
		{"Black Left Pointing Index", "\u261a"},
		{"Black Right Pointing Index", "\u261b"},
		{"White Left Pointing Index", "\u261c"},
		{"White Up Pointing Index", "\u261d"},
		{"White Right Pointing Index", "\u261e"},
		{"White Down Pointing Index", "\u261f"},
		{"Skull And Crossbones", "\u2620"},
		{"Caution Sign", "\u2621"},
		{"Radioactive Sign", "\u2622"},
		{"Biohazard Sign", "\u2623"},
		{"Caduceus", "\u2624"},
		{"Ankh", "\u2625"},
		{"Orthodox Cross", "\u2626"},
		{"Chi Rho", "\u2627"},
		{"Cross Of Lorraine", "\u2628"},
		{"Cross Of Jerusalem", "\u2629"},
		{"Star And Crescent", "\u262a"},
		{"Farsi Symbol", "\u262b"},
		{"Adi Shakti", "\u262c"},
		{"Hammer And Sickle", "\u262d"},
		{"Peace Symbol", "\u262e"},
		{"Yin Yang", "\u262f"},
		{"Trigram For Heaven", "\u2630"},
		{"Trigram For Lake", "\u2631"},
		{"Trigram For Fire", "\u2632"},
		{"Trigram For Thunder", "\u2633"},
		{"Trigram For Wind", "\u2634"},
		{"Trigram For Water", "\u2635"},
		{"Trigram For Mountain", "\u2636"},
		{"Trigram For Earth", "\u2637"},
		{"Wheel Of Dharma", "\u2638"},
		{"White Frowning Face", "\u2639"},
		{"White Smiling Face", "\u263a"},
		{"Black Smiling Face", "\u263b"},
		{"White Sun With Rays", "\u263c"},
		{"First Quarter Moon", "\u263d"},
		{"Last Quarter Moon", "\u263e"},
		{"Mercury", "\u263f"},
		{"Female Sign", "\u2640"},
		{"Earth", "\u2641"},
		{"Male Sign", "\u2642"},
		{"Jupiter", "\u2643"},
		{"Saturn", "\u2644"},
		{"Uranus", "\u2645"},
		{"Neptune", "\u2646"},
		{"Pluto", "\u2647"},
		{"Aries", "\u2648"},
		{"Taurus", "\u2649"},
		{"Gemini", "\u264a"},
		{"Cancer", "\u264b"},
		{"Leo", "\u264c"},
		{"Virgo", "\u264d"},
		{"Libra", "\u264e"},
		{"Scorpius", "\u264f"},
		{"Sagittarius", "\u2650"},
		{"Capricorn", "\u2651"},
		{"Aquarius", "\u2652"},
		{"Pisces", "\u2653"},
		{"White Chess King", "\u2654"},
		{"White Chess Queen", "\u2655"},
		{"White Chess Rook", "\u2656"},
		{"White Chess Bishop", "\u2657"},
		{"White Chess Knight", "\u2658"},
		{"White Chess Pawn", "\u2659"},
		{"Black Chess King", "\u265a"},
		{"Black Chess Queen", "\u265b"},
		{"Black Chess Rook", "\u265c"},
		{"Black Chess Bishop", "\u265d"},
		{"Black Chess Knight", "\u265e"},
		{"Black Chess Pawn", "\u265f"},
		{"Black Spade Suit", "\u2660"},
		{"White Heart Suit", "\u2661"},
		{"White Diamond Suit", "\u2662"},
		{"Black Club Suit", "\u2663"},
		{"White Spade Suit", "\u2664"},
		{"Black Heart Suit", "\u2665"},
		{"Black Diamond Suit", "\u2666"},
		{"White Club Suit", "\u2667"},
		{"Hot Springs", "\u2668"},
		{"Quarter Note", "\u2669"},
		{"Eighth Note", "\u266a"},
		{"Beamed Eighth Notes", "\u266b"},
		{"Beamed Sixteenth Notes", "\u266c"},
		{"Music Flat Sign", "\u266d"},
		{"Music Natural Sign", "\u266e"},
		{"Music Sharp Sign", "\u266f"},
		{"West Syriac Cross", "\u2670"},
		{"East Syriac Cross", "\u2671"},
		{"Universal Recycling Symbol", "\u2672"},
		{"Recycling Symbol For Type-1 Plastics", "\u2673"},
		{"Recycling Symbol For Type-2 Plastics", "\u2674"},
		{"Recycling Symbol For Type-3 Plastics", "\u2675"},
		{"Recycling Symbol For Type-4 Plastics", "\u2676"},
		{"Recycling Symbol For Type-5 Plastics", "\u2677"},
		{"Recycling Symbol For Type-6 Plastics", "\u2678"},
		{"Recycling Symbol For Type-7 Plastics", "\u2679"},
		{"Recycling Symbol For Generic Materials", "\u267a"},
		{"Black Universal Recycling Symbol", "\u267b"},
		{"Recycled Paper Symbol", "\u267c"},
		{"Partially-recycled Paper Symbol", "\u267d"},
		{"Permanent Paper Sign", "\u267e"},
		{"Wheelchair Symbol", "\u267f"},
		{"Die Face-1", "\u2680"},
		{"Die Face-2", "\u2681"},
		{"Die Face-3", "\u2682"},
		{"Die Face-4", "\u2683"},
		{"Die Face-5", "\u2684"},
		{"Die Face-6", "\u2685"},
		{"White Circle With Dot Right", "\u2686"},
		{"White Circle With Two Dots", "\u2687"},
		{"Black Circle With White Dot Right", "\u2688"},
		{"Black Circle With Two White Dots", "\u2689"},
		{"Monogram For Yang", "\u268a"},
		{"Monogram For Yin", "\u268b"},
		{"Digram For Greater Yang", "\u268c"},
		{"Digram For Lesser Yin", "\u268d"},
		{"Digram For Lesser Yang", "\u268e"},
		{"Digram For Greater Yin", "\u268f"},
		{"White Flag", "\u2690"},
		{"Black Flag", "\u2691"},
		{"Hammer And Pick", "\u2692"},
		{"Anchor", "\u2693"},
		{"Crossed Swords", "\u2694"},
		{"Staff Of Aesculapius", "\u2695"},
		{"Scales", "\u2696"},
		{"Alembic", "\u2697"},
		{"Flower", "\u2698"},
		{"Gear", "\u2699"},
		{"Staff Of Hermes", "\u269a"},
		{"Atom Symbol", "\u269b"},
		{"Fleur-de-lis", "\u269c"},
		{"Outlined White Star", "\u269d"},
		{"Three Lines Converging Right", "\u269e"},
		{"Three Lines Converging Left", "\u269f"},
		{"Warning Sign", "\u26a0"},
		{"High Voltage Sign", "\u26a1"},
		{"Doubled Female Sign", "\u26a2"},
		{"Doubled Male Sign", "\u26a3"},
		{"Interlocked Female And Male Sign", "\u26a4"},
		{"Male And Female Sign", "\u26a5"},
		{"Male With Stroke Sign", "\u26a6"},
		{"Male With Stroke And Male And Female Sign", "\u26a7"},
		{"Vertical Male With Stroke Sign", "\u26a8"},
		{"Horizontal Male With Stroke Sign", "\u26a9"},
		{"Medium White Circle", "\u26aa"},
		{"Medium Black Circle", "\u26ab"},
		{"Medium Small White Circle", "\u26ac"},
		{"Marriage Symbol", "\u26ad"},
		{"Divorce Symbol", "\u26ae"},
		{"Unmarried Partnership Symbol", "\u26af"},
		{"Coffin", "\u26b0"},
		{"Funeral Urn", "\u26b1"},
		{"Neuter", "\u26b2"},
		{"Ceres", "\u26b3"},
		{"Pallas", "\u26b4"},
		{"Juno", "\u26b5"},
		{"Vesta", "\u26b6"},
		{"Chiron", "\u26b7"},
		{"Black Moon Lilith", "\u26b8"},
		{"Sextile", "\u26b9"},
		{"Semisextile", "\u26ba"},
		{"Quincunx", "\u26bb"},
		{"Sesquiquadrate", "\u26bc"},
		{"Soccer Ball", "\u26bd"},
		{"Baseball", "\u26be"},
		{"Squared Key", "\u26bf"},
		{"White Draughts Man", "\u26c0"},
		{"White Draughts King", "\u26c1"},
		{"Black Draughts Man", "\u26c2"},
		{"Black Draughts King", "\u26c3"},
		{"Snowman Without Snow", "\u26c4"},
		{"Sun Behind Cloud", "\u26c5"},
		{"Rain", "\u26c6"},
		{"Black Snowman", "\u26c7"},
		{"Thunder Cloud And Rain", "\u26c8"},
		{"Turned White Shogi Piece", "\u26c9"},
		{"Turned Black Shogi Piece", "\u26ca"},
		{"White Diamond In Square", "\u26cb"},
		{"Crossing Lanes", "\u26cc"},
		{"Disabled Car", "\u26cd"},
		{"Ophiuchus", "\u26ce"},
		{"Pick", "\u26cf"},
		{"Car Sliding", "\u26d0"},
		{"Helmet With White Cross", "\u26d1"},
		{"Circled Crossing Lanes", "\u26d2"},
		{"Chains", "\u26d3"},
		{"No Entry", "\u26d4"},
		{"Alternate One-way Left Way Traffic", "\u26d5"},
		{"Black Two-way Left Way Traffic", "\u26d6"},
		{"White Two-way Left Way Traffic", "\u26d7"},
		{"Black Left Lane Merge", "\u26d8"},
		{"White Left Lane Merge", "\u26d9"},
		{"Drive Slow Sign", "\u26da"},
		{"Heavy White Down-pointing Triangle", "\u26db"},
		{"Left Closed Entry", "\u26dc"},
		{"Squared Saltire", "\u26dd"},
		{"Falling Diagonal In White Circle In Black Square", "\u26de"},
		{"Black Truck", "\u26df"},
		{"Restricted Left Entry-1", "\u26e0"},
		{"Restricted Left Entry-2", "\u26e1"},
		{"Astronomical Symbol For Uranus", "\u26e2"},
		{"Heavy Circle With Stroke And Two Dots Above", "\u26e3"},
		{"Pentagram", "\u26e4"},
		{"Right-handed Interlaced Pentagram", "\u26e5"},
		{"Left-handed Interlaced Pentagram", "\u26e6"},
		{"Inverted Pentagram", "\u26e7"},
		{"Black Cross On Shield", "\u26e8"},
		{"Shinto Shrine", "\u26e9"},
		{"Church", "\u26ea"},
		{"Castle", "\u26eb"},
		{"Historic Site", "\u26ec"},
		{"Gear Without Hub", "\u26ed"},
		{"Gear With Handles", "\u26ee"},
		{"Map Symbol For Lighthouse", "\u26ef"},
		{"Mountain", "\u26f0"},
		{"Umbrella On Ground", "\u26f1"},
		{"Fountain", "\u26f2"},
		{"Flag In Hole", "\u26f3"},
		{"Ferry", "\u26f4"},
		{"Sailboat", "\u26f5"},
		{"Square Four Corners", "\u26f6"},
		{"Skier", "\u26f7"},
		{"Ice Skate", "\u26f8"},
		{"Person With Ball", "\u26f9"},
		{"Tent", "\u26fa"},
		{"Japanese Bank Symbol", "\u26fb"},
		{"Headstone Graveyard Symbol", "\u26fc"},
		{"Fuel Pump", "\u26fd"},
		{"Cup On Black Square", "\u26fe"},
		{"White Flag With Horizontal Middle Black Stripe", "\u26ff"},
	}
}
