package main

import . "github.com/nbjahan/go-launchbar"

func addArrows() {
	var i *Item
	v := pb.GetView("main")

	arrows := [][2]string{
		{"Rightwards Arrow With Hook", "↪"},
		{"Leftwards Arrow With Hook", "↩"},
		{"Leftwards Arrow", "←"},
		{"Upwards Arrow", "↑"},
		{"Rightwards Arrow", "→"},
		{"Downwards Arrow", "↓"},
		{"Left Right Arrow", "↔"},
		{"Up Down Arrow", "↕"},
		{"North West Arrow", "↖"},
		{"North East Arrow", "↗"},
		{"South East Arrow", "↘"},
		{"South West Arrow", "↙"},
		{"Leftwards Arrow With Stroke", "↚"},
		{"Rightwards Arrow With Stroke", "↛"},
		{"Leftwards Wave Arrow", "↜"},
		{"Rightwards Wave Arrow", "↝"},
		{"Leftwards Two Headed Arrow", "↞"},
		{"Upwards Two Headed Arrow", "↟"},
		{"Rightwards Two Headed Arrow", "↠"},
		{"Downwards Two Headed Arrow", "↡"},
		{"Leftwards Arrow With Tail", "↢"},
		{"Rightwards Arrow With Tail", "↣"},
		{"Leftwards Arrow From Bar", "↤"},
		{"Rightwards Arrow From Bar", "↦"},
		{"Upwards Arrow From Bar", "↥"},
		{"Downwards Arrow From Bar", "↧"},
		{"Up Down Arrow With Base", "↨"},
		{"Leftwards Arrow With Loop", "↫"},
		{"Rightwards Arrow With Loop", "↬"},
		{"Left Right Wave Arrow", "↭"},
		{"Left Right Arrow With Stroke", "↮"},
		{"Downwards Zigzag Arrow", "↯"},
		{"Upwards Arrow With Tip Leftwards", "↰"},
		{"Upwards Arrow With Tip Rightwards", "↱"},
		{"Downwards Arrow With Tip Leftwards", "↲"},
		{"Rightwards Arrow With Corner Downwards", "↴"},
		{"Downwards Arrow With Tip Rightwards", "↳"},
		{"Downwards Arrow With Corner Leftwards", "↵"},
		{"Anticlockwise Top Semicircle Arrow", "↶"},
		{"Clockwise Top Semicircle Arrow", "↷"},
		{"North West Arrow To Long Bar", "↸"},
		{"Leftwards Arrow To Bar Over Rightwards Arrow To Bar", "↹"},
		{"Anticlockwise Open Circle Arrow", "↺"},
		{"Clockwise Open Circle Arrow", "↻"},
		{"Anticlockwise Gapped Circle Arrow", "⟲"},
		{"Clockwise Gapped Circle Arrow", "⟳"},
		{"Leftwards Harpoon With Barb Upwards", "↼"},
		{"Leftwards Harpoon With Barb Downwards", "↽"},
		{"Upwards Harpoon With Barb Rightwards", "↾"},
		{"Upwards Harpoon With Barb Leftwards", "↿"},
		{"Rightwards Harpoon With Barb Upwards", "⇀"},
		{"Rightwards Harpoon With Barb Downwards", "⇁"},
		{"Downwards Harpoon With Barb Rightwards", "⇂"},
		{"Downwards Harpoon With Barb Leftwards", "⇃"},
		{"Rightwards Arrow Over Leftwards Arrow", "⇄"},
		{"Upwards Arrow Leftwards Of Downwards Arrow", "⇅"},
		{"Leftwards Arrow Over Rightwards Arrow", "⇆"},
		{"Leftwards Paired Arrows", "⇇"},
		{"Upwards Paired Arrows", "⇈"},
		{"Rightwards Paired Arrows", "⇉"},
		{"Downwards Paired Arrows", "⇊"},
		{"Leftwards Harpoon Over Rightwards Harpoon", "⇋"},
		{"Rightwards Harpoon Over Leftwards Harpoon", "⇌"},
		{"Leftwards Double Arrow With Stroke", "⇍"},
		{"Rightwards Double Arrow With Stroke", "⇏"},
		{"Left Right Double Arrow With Stroke", "⇎"},
		{"Upwards Double Arrow", "⇑"},
		{"Downwards Double Arrow", "⇓"},
		{"Leftwards Double Arrow", "⇐"},
		{"Rightwards Double Arrow", "⇒"},
		{"Left Right Double Arrow", "⇔"},
		{"Up Down Double Arrow", "⇕"},
		{"North West Double Arrow", "⇖"},
		{"North East Double Arrow", "⇗"},
		{"South East Double Arrow", "⇘"},
		{"South West Double Arrow", "⇙"},
		{"Up Down White Arrow", "⇳"},
		{"Leftwards Triple Arrow", "⇚"},
		{"Rightwards Triple Arrow", "⇛"},
		{"Leftwards Squiggle Arrow", "⇜"},
		{"Rightwards Squiggle Arrow", "⇝"},
		{"Upwards Arrow With Double Stroke", "⇞"},
		{"Downwards Arrow With Double Stroke", "⇟"},
		{"Leftwards Dashed Arrow", "⇠"},
		{"Upwards Dashed Arrow", "⇡"},
		{"Rightwards Dashed Arrow", "⇢"},
		{"Downwards Dashed Arrow", "⇣"},
		{"Leftwards Arrow To Bar", "⇤"},
		{"Rightwards Arrow To Bar", "⇥"},
		{"Leftwards White Arrow", "⇦"},
		{"Rightwards White Arrow", "⇨"},
		{"Downwards White Arrow", "⇩"},
		{"Upwards White Arrow From Bar", "⇪"},
		{"Upwards White Arrow", "⇧"},
		{"Upwards White Arrow On Pedestal", "⇫"},
		{"Upwards White Arrow On Pedestal With Horizontal Bar", "⇬"},
		{"Upwards White Arrow On Pedestal With Vertical Bar", "⇭"},
		{"Upwards White Double Arrow", "⇮"},
		{"Upwards White Double Arrow On Pedestal", "⇯"},
		{"Rightwards White Arrow From Wall", "⇰"},
		{"North West Arrow To Corner", "⇱"},
		{"South East Arrow To Corner", "⇲"},
		{"Right Arrow With Small Circle", "⇴"},
		{"Downwards Arrow Leftwards Of Upwards Arrow", "⇵"},
		{"Three Rightwards Arrows", "⇶"},
		{"Leftwards Arrow With Vertical Stroke", "⇷"},
		{"Rightwards Arrow With Vertical Stroke", "⇸"},
		{"Left Right Arrow With Vertical Stroke", "⇹"},
		{"Leftwards Arrow With Double Vertical Stroke", "⇺"},
		{"Rightwards Arrow With Double Vertical Stroke", "⇻"},
		{"Left Right Arrow With Double Vertical Stroke", "⇼"},
		{"Leftwards Open Headed Arrow", "⇽"},
		{"Rightwards Open Headed Arrow", "⇾"},
		{"Left Right Open Headed Arrow", "⇿"},
		{"Upwards Quadruple Arrow", "⟰"},
		{"Downwards Quadruple Arrow", "⟱"},
		{"Right Arrow With Circled Plus", "⟴"},
		{"Long Leftwards Arrow", "⟵"},
		{"Long Rightwards Arrow", "⟶"},
		{"Long Left Right Arrow", "⟷"},
		{"Long Leftwards Double Arrow", "⟸"},
		{"Long Rightwards Double Arrow", "⟹"},
		{"Long Leftwards Double Arrow From Bar", "⟽"},
		{"Long Rightwards Double Arrow From Bar", "⟾"},
		{"Long Left Right Double Arrow", "⟺"},
		{"Long Leftwards Arrow From Bar", "⟻"},
		{"Long Rightwards Arrow From Bar", "⟼"},
		{"Long Rightwards Squiggle Arrow", "⟿"},
		{"Rightwards Two Headed Arrow With Vertical Stroke", "⤀"},
		{"Rightwards Two Headed Arrow With Double Vertical Stroke", "⤁"},
		{"Rightwards Two Headed Arrow From Bar", "⤅"},
		{"Leftwards Double Arrow With Vertical Stroke", "⤂"},
		{"Rightwards Double Arrow With Vertical Stroke", "⤃"},
		{"Left Right Double Arrow With Vertical Stroke", "⤄"},
		{"Leftwards Double Arrow From Bar", "⤆"},
		{"Rightwards Double Arrow From Bar", "⤇"},
		{"Downwards Arrow With Horizontal Stroke", "⤈"},
		{"Upwards Arrow With Horizontal Stroke", "⤉"},
		{"Upwards Triple Arrow", "⤊"},
		{"Downwards Triple Arrow", "⤋"},
		{"Leftwards Double Dash Arrow", "⤌"},
		{"Rightwards Double Dash Arrow", "⤍"},
		{"Leftwards Triple Dash Arrow", "⤎"},
		{"Rightwards Triple Dash Arrow", "⤏"},
		{"Rightwards Two Headed Triple Dash Arrow", "⤐"},
		{"Rightwards Arrow With Dotted Stem", "⤑"},
		{"Upwards Arrow To Bar", "⤒"},
		{"Downwards Arrow To Bar", "⤓"},
		{"Rightwards Arrow With Tail With Vertical Stroke", "⤔"},
		{"Rightwards Arrow With Tail With Double Vertical Stroke", "⤕"},
		{"Rightwards Two Headed Arrow With Tail", "⤖"},
		{"Rightwards Two Headed Arrow With Tail With Vertical Stroke", "⤗"},
		{"Rightwards Two Headed Arrow With Tail With Double Vertical Stroke", "⤘"},
		{"Leftwards Arrow Tail", "⤙"},
		{"Rightwards Arrow Tail", "⤚"},
		{"Leftwards Double Arrow Tail", "⤛"},
		{"Rightwards Double Arrow Tail", "⤜"},
		{"Leftwards Arrow To Black Diamond", "⤝"},
		{"Rightwards Arrow To Black Diamond", "⤞"},
		{"Leftwards Arrow From Bar To Black Diamond", "⤟"},
		{"Rightwards Arrow From Bar To Black Diamond", "⤠"},
		{"North West And South East Arrow", "⤡"},
		{"North East And South West Arrow", "⤢"},
		{"North West Arrow With Hook", "⤣"},
		{"North East Arrow With Hook", "⤤"},
		{"South East Arrow With Hook", "⤥"},
		{"South West Arrow With Hook", "⤦"},
		{"North West Arrow And North East Arrow", "⤧"},
		{"North East Arrow And South East Arrow", "⤨"},
		{"South East Arrow And South West Arrow", "⤩"},
		{"South West Arrow And North West Arrow", "⤪"},
		{"South East Arrow Crossing North East Arrow", "⤭"},
		{"North East Arrow Crossing South East Arrow", "⤮"},
		{"Falling Diagonal Crossing North East Arrow", "⤯"},
		{"Rising Diagonal Crossing South East Arrow", "⤰"},
		{"North East Arrow Crossing North West Arrow", "⤱"},
		{"North West Arrow Crossing North East Arrow", "⤲"},
		{"Wave Arrow Pointing Directly Right", "⤳"},
		{"Bottom Arc Anticlockwise Arrow", "⤻"},
		{"Right Side Arc Clockwise Arrow", "⤸"},
		{"Lower Right Semicircular Clockwise Arrow", "⤾"},
		{"Lower Left Semicircular Anticlockwise Arrow", "⤿"},
		{"Top Arc Anticlockwise Arrow", "⤺"},
		{"Top Arc Clockwise Arrow With Minus", "⤼"},
		{"Top Arc Anticlockwise Arrow With Plus", "⤽"},
		{"Arrow Pointing Rightwards Then Curving Upwards", "⤴"},
		{"Arrow Pointing Rightwards Then Curving Downwards", "⤵"},
		{"Arrow Pointing Downwards Then Curving Leftwards", "⤶"},
		{"Arrow Pointing Downwards Then Curving Rightwards", "⤷"},
		{"Left Side Arc Anticlockwise Arrow", "⤹"},
		{"Anticlockwise Closed Circle Arrow", "⥀"},
		{"Clockwise Closed Circle Arrow", "⥁"},
		{"Rightwards Arrow Above Short Leftwards Arrow", "⥂"},
		{"Leftwards Arrow Above Short Rightwards Arrow", "⥃"},
		{"Short Rightwards Arrow Above Leftwards Arrow", "⥄"},
		{"Rightwards Arrow With Plus Below", "⥅"},
		{"Leftwards Arrow With Plus Below", "⥆"},
		{"Rightwards Arrow Through X", "⥇"},
		{"Left Right Arrow Through Small Circle", "⥈"},
		{"Upwards Two Headed Arrow From Small Circle", "⥉"},
		{"Leftwards Harpoon With Barb Up To Bar", "⥒"},
		{"Rightwards Harpoon With Barb Up To Bar", "⥓"},
		{"Upwards Harpoon With Barb Right To Bar", "⥔"},
		{"Downwards Harpoon With Barb Right To Bar", "⥕"},
		{"Leftwards Harpoon With Barb Down To Bar", "⥖"},
		{"Rightwards Harpoon With Barb Down To Bar", "⥗"},
		{"Upwards Harpoon With Barb Left To Bar", "⥘"},
		{"Downwards Harpoon With Barb Left To Bar", "⥙"},
		{"Leftwards Harpoon With Barb Up From Bar", "⥚"},
		{"Rightwards Harpoon With Barb Up From Bar", "⥛"},
		{"Upwards Harpoon With Barb Right From Bar", "⥜"},
		{"Downwards Harpoon With Barb Right From Bar", "⥝"},
		{"Leftwards Harpoon With Barb Down From Bar", "⥞"},
		{"Rightwards Harpoon With Barb Down From Bar", "⥟"},
		{"Upwards Harpoon With Barb Left From Bar", "⥠"},
		{"Downwards Harpoon With Barb Left From Bar", "⥡"},
		{"Leftwards Harpoon With Barb Up Above Leftwards Harpoon With Barb Down", "⥢"},
		{"Upwards Harpoon With Barb Left Beside Upwards Harpoon With Barb Right", "⥣"},
		{"Rightwards Harpoon With Barb Up Above Rightwards Harpoon With Barb Down", "⥤"},
		{"Downwards Harpoon With Barb Left Beside Downwards Harpoon With Barb Right", "⥥"},
		{"Leftwards Harpoon With Barb Up Above Rightwards Harpoon With Barb Up", "⥦"},
		{"Leftwards Harpoon With Barb Down Above Rightwards Harpoon With Barb Down", "⥧"},
		{"Rightwards Harpoon With Barb Up Above Leftwards Harpoon With Barb Up", "⥨"},
		{"Rightwards Harpoon With Barb Down Above Leftwards Harpoon With Barb Down", "⥩"},
		{"Leftwards Harpoon With Barb Up Above Long Dash", "⥪"},
		{"Leftwards Harpoon With Barb Down Below Long Dash", "⥫"},
		{"Rightwards Harpoon With Barb Up Above Long Dash", "⥬"},
		{"Rightwards Harpoon With Barb Down Below Long Dash", "⥭"},
		{"Upwards Harpoon With Barb Left Beside Downwards Harpoon With Barb Right", "⥮"},
		{"Downwards Harpoon With Barb Left Beside Upwards Harpoon With Barb Right", "⥯"},
		{"Right Double Arrow With Rounded Head", "⥰"},
		{"Equals Sign Above Rightwards Arrow", "⥱"},
		{"Tilde Operator Above Rightwards Arrow", "⥲"},
		{"Leftwards Arrow Above Tilde Operator", "⥳"},
		{"Rightwards Arrow Above Tilde Operator", "⥴"},
		{"Rightwards Arrow Above Almost Equal To", "⥵"},
		{"Less Than Above Leftwards Arrow", "⥶"},
		{"Leftwards Arrow Through Less Than", "⥷"},
		{"Greater Than Above Rightwards Arrow", "⥸"},
		{"Subset Above Rightwards Arrow", "⥹"},
		{"Leftwards Arrow Through Subset", "⥺"},
		{"Superset Above Leftwards Arrow", "⥻"},
		{"Heavy Wide Headed Rightwards Arrow", "➔"},
		{"Heavy South East Arrow", "➘"},
		{"Heavy Rightwards Arrow", "➙"},
		{"Heavy North East Arrow", "➚"},
		{"Drafting Point Rightwards Arrow", "➛"},
		{"Heavy Round Tipped Rightwards Arrow", "➜"},
		{"Triangle Headed Rightwards Arrow", "➝"},
		{"Heavy Triangle Headed Rightwards Arrow", "➞"},
		{"Dashed Triangle Headed Rightwards Arrow", "➟"},
		{"Heavy Dashed Triangle Headed Rightwards Arrow", "➠"},
		{"Black Rightwards Arrow", "➡"},
		{"Three D Top Lighted Rightwards Arrowhead", "➢"},
		{"Three D Bottom Lighted Rightwards Arrowhead", "➣"},
		{"Black Rightwards Arrowhead", "➤"},
		{"Heavy Black Curved Downwards And Rightwards Arrow", "➥"},
		{"Heavy Black Curved Upwards And Rightwards Arrow", "➦"},
		{"Squat Black Rightwards Arrow", "➧"},
		{"Heavy Concave Pointed Black Rightwards Arrow", "➨"},
		{"Right Shaded White Rightwards Arrow", "➩"},
		{"Left Shaded White Rightwards Arrow", "➪"},
		{"Back Tilted Shadowed White Rightwards Arrow", "➫"},
		{"Front Tilted Shadowed White Rightwards Arrow", "➬"},
		{"Heavy Lower Right Shadowed White Rightwards Arrow", "➭"},
		{"Heavy Upper Right Shadowed White Rightwards Arrow", "➮"},
		{"Notched Lower Right Shadowed White Rightwards Arrow", "➯"},
		{"Notched Upper Right Shadowed White Rightwards Arrow", "➱"},
		{"Circled Heavy White Rightwards Arrow", "➲"},
		{"White Feathered Rightwards Arrow", "➳"},
		{"Black Feathered South East Arrow", "➴"},
		{"Black Feathered Rightwards Arrow", "➵"},
		{"Black Feathered North East Arrow", "➶"},
		{"Heavy Black Feathered South East Arrow", "➷"},
		{"Heavy Black Feathered Rightwards Arrow", "➸"},
		{"Heavy Black Feathered North East Arrow", "➹"},
		{"Teardrop Barbed Rightwards Arrow", "➺"},
		{"Heavy Teardrop Shanked Rightwards Arrow", "➻"},
		{"Wedge Tailed Rightwards Arrow", "➼"},
		{"Heavy Wedge Tailed Rightwards Arrow", "➽"},
		{"Open Outlined Rightwards Arrow", "➾"},
		{"North East White Arrow", "⬀"},
		{"North West White Arrow", "⬁"},
		{"South East White Arrow", "⬂"},
		{"South West White Arrow", "⬃"},
		{"Left Right White Arrow", "⬄"},
		{"Leftwards Black Arrow", "⬅"},
		{"Upwards Black Arrow", "⬆"},
		{"Downwards Black Arrow", "⬇"},
		{"North East Black Arrow", "⬈"},
		{"North West Black Arrow", "⬉"},
		{"South East Black Arrow", "⬊"},
		{"South West Black Arrow", "⬋"},
		{"Left Right Black Arrow", "⬌"},
		{"Up Down Black Arrow", "⬍"},
		{"Return Symbol", "⏎"},
		{"Black Up Pointing Triangle", "▲"},
		{"Black Down Pointing Triangle", "▼"},
		{"Black Left Pointing Triangle", "◀"},
		{"Black Right Pointing Triangle", "▶"},
		{"Rightwards Arrow With Tip Downwards", "⬎"},
		{"Rightwards Arrow With Tip Upwards", "⬏"},
		{"Leftwards Arrow With Tip Downwards", "⬐"},
		{"Leftwards Arrow With Tip Upwards", "⬑"},
		{"Lightning", "☇"},
		{"Thunderstorm", "☈"},
		{"Apl Functional Symbol Quad Less Than", "⍃"},
		{"Apl Functional Symbol Quad Greater Than", "⍄"},
		{"Apl Functional Symbol Quad Leftwards Arrow", "⍇"},
		{"Apl Functional Symbol Quad Rightwards Arrow", "⍈"},
		{"Apl Functional Symbol Quad Upwards Arrow", "⍐"},
		{"Apl Functional Symbol Quad Downwards Arrow", "⍗"},
		{"Apl Functional Symbol Quad Down Caret", "⍌"},
		{"Apl Functional Symbol Quad Up Caret", "⍓"},
		{"Apl Functional Symbol Quad Delta", "⍍"},
		{"Apl Functional Symbol Quad Del", "⍔"},
		{"Apl Functional Symbol Upwards Vane", "⍏"},
		{"Apl Functional Symbol Downwards Vane", "⍖"},
		{"Apl Functional Symbol Leftwards Vane", "⍅"},
		{"Apl Functional Symbol Rightwards Vane", "⍆"},
	}
	i = v.NewItem("Arrows")
	i.SetIcon(iconPath("arrows", "Downwards-Zigzag-Arrow"))
	i.SetActionRunsInBackground(false)
	i.SetActionReturnsItems(true)
	i.SetRun(func(c *Context) Items {
		items := NewItems()
		for _, row := range arrows {
			i := NewItem(row[0])
			i.SetIcon(iconPath("arrows", row[0]))
			i.Run("showChar", row[0], row[1])
			i.SetAction("unisym")
			i.SetActionReturnsItems(true)
			i.SetActionRunsInBackground(false)
			items.Add(i)
		}
		return *items
	})
}
