package main

import . "github.com/nbjahan/go-launchbar"

func addClassics() {
	var i *Item
	v := pb.GetView("main")

	chars := [][2]string{
		{"Place Of Interest Sign", "⌘"},
		{"Left Pointing Double Angle Quotation Mark", "«"},
		{"Right Pointing Double Angle Quotation Mark", "»"},
		{"Single Left Pointing Angle Quotation Mark", "‹"},
		{"Single Right Pointing Angle Quotation Mark", "›"},
		{"Left Single Quotation Mark", "‘"},
		{"Right Single Quotation Mark", "’"},
		{"Left Double Quotation Mark", "“"},
		{"Right Double Quotation Mark", "”"},
		{"Double Low 9 Quotation Mark", "„"},
		{"Single Low 9 Quotation Mark", "‚"},
		{"Heavy Double Turned Comma Quotation Mark Ornament", "❝"},
		{"Heavy Double Comma Quotation Mark Ornament", "❞"},
		{"Pound Sign", "£"},
		{"Yen Sign", "¥"},
		{"Euro Sign", "€"},
		{"Dollar Sign", "$"},
		{"Cent Sign", "¢"},
		{"Not Sign", "¬"},
		{"Pilcrow Sign", "¶"},
		{"Commercial At", "@"},
		{"Section Sign", "§"},
		{"Registered Sign", "®"},
		{"Copyright Sign", "©"},
		{"Trade Mark Sign", "™"},
		{"Degree Sign", "°"},
		{"Multiplication Sign", "×"},
		{"Greek Small Letter Pi", "π"},
		{"Plus Minus Sign", "±"},
		{"Square Root", "√"},
		{"Per Mille Sign", "‰"},
		{"Greek Capital Letter Omega", "Ω"},
		{"Infinity", "∞"},
		{"Almost Equal To", "≈"},
		{"Division Sign", "÷"},
		{"Tilde", "~"},
		{"Not Equal To", "≠"},
		{"Superscript One", "¹"},
		{"Superscript Two", "²"},
		{"Superscript Three", "³"},
		{"Vulgar Fraction One Half", "½"},
		{"Vulgar Fraction One Quarter", "¼"},
		{"Vulgar Fraction Three Quarters", "¾"},
		{"Hyphen", "‐"},
		{"En Dash", "–"},
		{"Em Dash", "—"},
		{"Vertical Line", "|"},
		{"Fraction Slash", "⁄"},
		{"Reverse Solidus", "\\"},
		{"Left Square Bracket", "["},
		{"Right Square Bracket", "]"},
		{"Left Curly Bracket", "{"},
		{"Right Curly Bracket", "}"},
		{"Dagger", "†"},
		{"Double Dagger", "‡"},
		{"Horizontal Ellipsis", "…"},
		{"Middle Dot", "·"},
		{"Bullet", "•"},
		{"Black Circle", "●"},
		{"", ""},
		{"Option Key", "⌥"},
		{"Up Arrowhead", "⌃"},
		{"Upwards White Arrow", "⇧"},
		{"Leftwards Arrow With Hook", "↩"},
		{"Inverted Exclamation Mark", "¡"},
		{"Inverted Question Mark", "¿"},
		{"Interrobang", "‽"},
		{"Asterism", "⁂"},
		{"Therefore", "∴"},
		{"Because", "∵"},
		{"Lozenge", "◊"},
		{"Reference Mark", "※"},
		{"Leftwards Arrow", "←"},
		{"Rightwards Arrow", "→"},
		{"Upwards Arrow", "↑"},
		{"Downwards Arrow", "↓"},
		{"White Left Pointing Index", "☜"},
		{"White Right Pointing Index", "☞"},
		{"White Up Pointing Index", "☝"},
		{"White Down Pointing Index", "☟"},
		{"Heavy Check Mark", "✔"},
		{"Black Star", "★"},
		{"White Star", "☆"},
		{"Recycling Symbol For Generic Materials", "♺"},
		{"White Sun With Rays", "☼"},
		{"Umbrella", "☂"},
		{"White Smiling Face", "☺"},
		{"White Frowning Face", "☹"},
		{"Snowman", "☃"},
		{"Envelope", "✉"},
		{"Black Florette", "✿"},
		{"White Scissors", "✄"},
		{"Airplane", "✈"},
		{"Victory Hand", "✌"},
		{"Lower Right Pencil", "✎"},
		{"Black Spade Suit", "♠"},
		{"Black Diamond Suit", "♦"},
		{"Black Club Suit", "♣"},
		{"Black Heart Suit", "♥"},
		{"Eighth Note", "♪"},
		{"Beamed Eighth Notes", "♫"},
		{"Music Sharp Sign", "♯"},
		{"Female Sign", "♀"},
		{"Male Sign", "♂"},
		{"Greek Small Letter Alpha", "α"},
		{"Latin Small Letter Sharp S", "ß"},
		{"Latin Capital Letter A With Acute", "Á"},
		{"Latin Small Letter A With Acute", "á"},
		{"Latin Capital Letter A With Grave", "À"},
		{"Latin Small Letter A With Grave", "à"},
		{"Latin Capital Letter A With Ring Above", "Å"},
		{"Latin Small Letter A With Ring Above", "å"},
		{"Latin Capital Letter A With Diaeresis", "Ä"},
		{"Latin Small Letter A With Diaeresis", "ä"},
		{"Latin Capital Letter Ae", "Æ"},
		{"Latin Small Letter Ae", "æ"},
		{"Latin Capital Letter C With Cedilla", "Ç"},
		{"Latin Small Letter C With Cedilla", "ç"},
		{"Latin Capital Letter E With Acute", "É"},
		{"Latin Small Letter E With Acute", "é"},
		{"Latin Capital Letter E With Grave", "È"},
		{"Latin Small Letter E With Grave", "è"},
		{"Latin Capital Letter E With Circumflex", "Ê"},
		{"Latin Small Letter E With Circumflex", "ê"},
		{"Latin Capital Letter I With Acute", "Í"},
		{"Latin Small Letter I With Acute", "í"},
		{"Latin Capital Letter I With Grave", "Ì"},
		{"Latin Small Letter I With Grave", "ì"},
		{"Latin Capital Letter I With Circumflex", "Î"},
		{"Latin Small Letter I With Circumflex", "î"},
		{"Latin Capital Letter N With Tilde", "Ñ"},
		{"Latin Small Letter N With Tilde", "ñ"},
		{"Latin Capital Letter O With Acute", "Ó"},
		{"Latin Small Letter O With Acute", "ó"},
		{"Latin Capital Letter O With Grave", "Ò"},
		{"Latin Small Letter O With Grave", "ò"},
		{"Latin Capital Letter O With Circumflex", "Ô"},
		{"Latin Small Letter O With Circumflex", "ô"},
		{"Latin Capital Letter O With Diaeresis", "Ö"},
		{"Latin Small Letter O With Diaeresis", "ö"},
		{"Latin Capital Letter O With Stroke", "Ø"},
		{"Latin Small Letter O With Stroke", "ø"},
		{"Latin Capital Letter U With Acute", "Ú"},
		{"Latin Small Letter U With Acute", "ú"},
		{"Latin Capital Letter U With Grave", "Ù"},
		{"Latin Small Letter U With Grave", "ù"},
		{"Latin Capital Letter U With Diaeresis", "Ü"},
		{"Latin Small Letter U With Diaeresis", "ü"},
		{"Latin Capital Letter Z With Caron", "Ž"},
		{"Latin Small Letter Z With Caron", "ž"},
	}
	i = v.NewItem("Classics")
	i.SetIcon(iconPath("classics", "Eighth Note"))
	i.SetActionRunsInBackground(false)
	i.SetActionReturnsItems(true)
	i.SetRun(func(c *Context) Items {
		items := NewItems()
		for _, row := range chars {
			i := NewItem(row[0])
			i.SetIcon(iconPath("classics", row[0]))
			i.Run("showChar", row[0], row[1])
			i.SetAction("unisym")
			i.SetActionReturnsItems(true)
			i.SetActionRunsInBackground(false)
			items.Add(i)
		}
		return *items
	})
}
