package main

import . "github.com/nbjahan/go-launchbar"

func addMath() {
	var i *Item
	v := pb.GetView("main")

	chars := [][2]string{
		{"Infinity", "∞"},
		{"Three Dimensional Angle", "⟀"},
		{"White Triangle Containing Small White Triangle", "⟁"},
		{"Perpendicular", "⟂"},
		{"Open Subset", "⟃"},
		{"Open Superset", "⟄"},
		{"Or With Dot Inside", "⟇"},
		{"Reverse Solidus Preceding Subset", "⟈"},
		{"Superset Preceding Solidus", "⟉"},
		{"Vertical Bar With Horizontal Stroke", "⟊"},
		{"White Diamond With Centred Dot", "⟐"},
		{"And With Dot", "⟑"},
		{"Element Of Opening Upwards", "⟒"},
		{"Lower Right Corner With Dot", "⟓"},
		{"Upper Left Corner With Dot", "⟔"},
		{"Left Outer Join", "⟕"},
		{"Right Outer Join", "⟖"},
		{"Full Outer Join", "⟗"},
		{"Large Up Tack", "⟘"},
		{"Large Down Tack", "⟙"},
		{"Left And Right Double Turnstile", "⟚"},
		{"Left And Right Tack", "⟛"},
		{"Left Multimap", "⟜"},
		{"Long Right Tack", "⟝"},
		{"Long Left Tack", "⟞"},
		{"Up Tack With Circle Above", "⟟"},
		{"Lozenge Divided By Horizontal Rule", "⟠"},
		{"White Concave Sided Diamond", "⟡"},
		{"White Concave Sided Diamond With Leftwards Tick", "⟢"},
		{"White Concave Sided Diamond With Rightwards Tick", "⟣"},
		{"White Square With Leftwards Tick", "⟤"},
		{"White Square With Rightwards Tick", "⟥"},
		{"Mathematical Left White Square Bracket", "⟦"},
		{"Mathematical Right White Square Bracket", "⟧"},
		{"Mathematical Left Angle Bracket", "⟨"},
		{"Mathematical Right Angle Bracket", "⟩"},
		{"Mathematical Left Double Angle Bracket", "⟪"},
		{"Mathematical Right Double Angle Bracket", "⟫"},
		{"Triple Vertical Bar Delimiter", "⦀"},
		{"Z Notation Spot", "⦁"},
		{"Z Notation Type Colon", "⦂"},
		{"Left White Curly Bracket", "⦃"},
		{"Right White Curly Bracket", "⦄"},
		{"Left White Parenthesis", "⦅"},
		{"Right White Parenthesis", "⦆"},
		{"Z Notation Left Image Bracket", "⦇"},
		{"Z Notation Right Image Bracket", "⦈"},
		{"Z Notation Left Binding Bracket", "⦉"},
		{"Z Notation Right Binding Bracket", "⦊"},
		{"Left Square Bracket With Underbar", "⦋"},
		{"Right Square Bracket With Underbar", "⦌"},
		{"Left Square Bracket With Tick In Top Corner", "⦍"},
		{"Right Square Bracket With Tick In Bottom Corner", "⦎"},
		{"Left Square Bracket With Tick In Bottom Corner", "⦏"},
		{"Right Square Bracket With Tick In Top Corner", "⦐"},
		{"Left Angle Bracket With Dot", "⦑"},
		{"Right Angle Bracket With Dot", "⦒"},
		{"Left Arc Less Than Bracket", "⦓"},
		{"Right Arc Greater Than Bracket", "⦔"},
		{"Double Left Arc Greater Than Bracket", "⦕"},
		{"Double Right Arc Less Than Bracket", "⦖"},
		{"Left Black Tortoise Shell Bracket", "⦗"},
		{"Right Black Tortoise Shell Bracket", "⦘"},
		{"Dotted Fence", "⦙"},
		{"Vertical Zigzag Line", "⦚"},
		{"Measured Angle Opening Left", "⦛"},
		{"Right Angle Variant With Square", "⦜"},
		{"Measured Right Angle With Dot", "⦝"},
		{"Angle With S Inside", "⦞"},
		{"Acute Angle", "⦟"},
		{"Spherical Angle Opening Left", "⦠"},
		{"Spherical Angle Opening Up", "⦡"},
		{"Turned Angle", "⦢"},
		{"Reversed Angle", "⦣"},
		{"Angle With Underbar", "⦤"},
		{"Reversed Angle With Underbar", "⦥"},
		{"Oblique Angle Opening Up", "⦦"},
		{"Oblique Angle Opening Down", "⦧"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Up And Right", "⦨"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Up And Left", "⦩"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Down And Right", "⦪"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Down And Left", "⦫"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Right And Up", "⦬"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Left And Up", "⦭"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Right And Down", "⦮"},
		{"Measured Angle With Open Arm Ending In Arrow Pointing Left And Down", "⦯"},
		{"Reversed Empty Set", "⦰"},
		{"Empty Set With Overbar", "⦱"},
		{"Empty Set With Small Circle Above", "⦲"},
		{"Empty Set With Right Arrow Above", "⦳"},
		{"Empty Set With Left Arrow Above", "⦴"},
		{"Circle With Horizontal Bar", "⦵"},
		{"Circled Vertical Bar", "⦶"},
		{"Circled Parallel", "⦷"},
		{"Circled Reverse Solidus", "⦸"},
		{"Circled Perpendicular", "⦹"},
		{"Circle Divided By Horizontal Bar And Top Half Divided By Vertical Bar", "⦺"},
		{"Circle With Superimposed X", "⦻"},
		{"Circled Anticlockwise Rotated Division Sign", "⦼"},
		{"Up Arrow Through Circle", "⦽"},
		{"Circled White Bullet", "⦾"},
		{"Circled Bullet", "⦿"},
		{"Circled Less Than", "⧀"},
		{"Circled Greater Than", "⧁"},
		{"Circle With Small Circle To The Right", "⧂"},
		{"Circle With Two Horizontal Strokes To The Right", "⧃"},
		{"Squared Rising Diagonal Slash", "⧄"},
		{"Squared Falling Diagonal Slash", "⧅"},
		{"Squared Asterisk", "⧆"},
		{"Squared Small Circle", "⧇"},
		{"Squared Square", "⧈"},
		{"Two Joined Squares", "⧉"},
		{"Triangle With Dot Above", "⧊"},
		{"Triangle With Underbar", "⧋"},
		{"S In Triangle", "⧌"},
		{"Triangle With Serifs At Bottom", "⧍"},
		{"Right Triangle Above Left Triangle", "⧎"},
		{"Left Triangle Beside Vertical Bar", "⧏"},
		{"Vertical Bar Beside Right Triangle", "⧐"},
		{"Bowtie With Left Half Black", "⧑"},
		{"Bowtie With Right Half Black", "⧒"},
		{"Black Bowtie", "⧓"},
		{"Times With Left Half Black", "⧔"},
		{"Times With Right Half Black", "⧕"},
		{"White Hourglass", "⧖"},
		{"Black Hourglass", "⧗"},
		{"Left Wiggly Fence", "⧘"},
		{"Right Wiggly Fence", "⧙"},
		{"Left Double Wiggly Fence", "⧚"},
		{"Right Double Wiggly Fence", "⧛"},
		{"Incomplete Infinity", "⧜"},
		{"Tie Over Infinity", "⧝"},
		{"Infinity Negated With Vertical Bar", "⧞"},
		{"Double Ended Multimap", "⧟"},
		{"Increases As", "⧡"},
		{"Shuffle Product", "⧢"},
		{"Equals Sign And Slanted Parallel", "⧣"},
		{"Equals Sign And Slanted Parallel With Tilde Above", "⧤"},
		{"Identical To And Slanted Parallel", "⧥"},
		{"Gleich Stark", "⧦"},
		{"Thermodynamic", "⧧"},
		{"Down Pointing Triangle With Left Half Black", "⧨"},
		{"Down Pointing Triangle With Right Half Black", "⧩"},
		{"Black Diamond With Down Arrow", "⧪"},
		{"Black Lozenge", "⧫"},
		{"White Circle With Down Arrow", "⧬"},
		{"Black Circle With Down Arrow", "⧭"},
		{"Error Barred White Square", "⧮"},
		{"Error Barred Black Square", "⧯"},
		{"Error Barred White Diamond", "⧰"},
		{"Error Barred Black Diamond", "⧱"},
		{"Error Barred White Circle", "⧲"},
		{"Error Barred Black Circle", "⧳"},
		{"Rule Delayed", "⧴"},
		{"Reverse Solidus Operator", "⧵"},
		{"Solidus With Overbar", "⧶"},
		{"Reverse Solidus With Horizontal Stroke", "⧷"},
		{"Big Solidus", "⧸"},
		{"Big Reverse Solidus", "⧹"},
		{"Double Plus", "⧺"},
		{"Triple Plus", "⧻"},
		{"Left Pointing Curved Angle Bracket", "⧼"},
		{"Right Pointing Curved Angle Bracket", "⧽"},
		{"Tiny", "⧾"},
		{"Miny", "⧿"},
		{"For All", "∀"},
		{"Complement", "∁"},
		{"Partial Differential", "∂"},
		{"There Exists", "∃"},
		{"There Does Not Exist", "∄"},
		{"Empty Set", "∅"},
		{"Increment", "∆"},
		{"Nabla", "∇"},
		{"Element Of", "∈"},
		{"Not An Element Of", "∉"},
		{"Small Element Of", "∊"},
		{"Contains As Member", "∋"},
		{"Does Not Contain As Member", "∌"},
		{"Small Contains As Member", "∍"},
		{"End Of Proof", "∎"},
		{"N Ary Product", "∏"},
		{"N Ary Coproduct", "∐"},
		{"N Ary Summation", "∑"},
		{"Minus Sign", "−"},
		{"Minus Or Plus Sign", "∓"},
		{"Dot Plus", "∔"},
		{"Division Slash", "∕"},
		{"Set Minus", "∖"},
		{"Asterisk Operator", "∗"},
		{"Ring Operator", "∘"},
		{"Bullet Operator", "∙"},
		{"Square Root", "√"},
		{"Cube Root", "∛"},
		{"Fourth Root", "∜"},
		{"Proportional To", "∝"},
		{"Right Angle", "∟"},
		{"Angle", "∠"},
		{"Measured Angle", "∡"},
		{"Spherical Angle", "∢"},
		{"Divides", "∣"},
		{"Does Not Divide", "∤"},
		{"Parallel To", "∥"},
		{"Not Parallel To", "∦"},
		{"Logical And", "∧"},
		{"Logical Or", "∨"},
		{"Intersection", "∩"},
		{"Union", "∪"},
		{"Integral", "∫"},
		{"Double Integral", "∬"},
		{"Triple Integral", "∭"},
		{"Contour Integral", "∮"},
		{"Surface Integral", "∯"},
		{"Volume Integral", "∰"},
		{"Clockwise Integral", "∱"},
		{"Clockwise Contour Integral", "∲"},
		{"Anticlockwise Contour Integral", "∳"},
		{"Therefore", "∴"},
		{"Because", "∵"},
		{"Ratio", "∶"},
		{"Proportion", "∷"},
		{"Dot Minus", "∸"},
		{"Excess", "∹"},
		{"Geometric Proportion", "∺"},
		{"Homothetic", "∻"},
		{"Tilde Operator", "∼"},
		{"Reversed Tilde", "∽"},
		{"Inverted Lazy S", "∾"},
		{"Sine Wave", "∿"},
		{"Wreath Product", "≀"},
		{"Not Tilde", "≁"},
		{"Minus Tilde", "≂"},
		{"Asymptotically Equal To", "≃"},
		{"Not Asymptotically Equal To", "≄"},
		{"Approximately Equal To", "≅"},
		{"Approximately But Not Actually Equal To", "≆"},
		{"Neither Approximately Nor Actually Equal To", "≇"},
		{"Almost Equal To", "≈"},
		{"Not Almost Equal To", "≉"},
		{"Almost Equal Or Equal To", "≊"},
		{"Triple Tilde", "≋"},
		{"All Equal To", "≌"},
		{"Equivalent To", "≍"},
		{"Geometrically Equivalent To", "≎"},
		{"Difference Between", "≏"},
		{"Approaches The Limit", "≐"},
		{"Geometrically Equal To", "≑"},
		{"Approximately Equal To Or The Image Of", "≒"},
		{"Image Of Or Approximately Equal To", "≓"},
		{"Colon Equals", "≔"},
		{"Equals Colon", "≕"},
		{"Ring In Equal To", "≖"},
		{"Ring Equal To", "≗"},
		{"Corresponds To", "≘"},
		{"Estimates", "≙"},
		{"Equiangular To", "≚"},
		{"Star Equals", "≛"},
		{"Delta Equal To", "≜"},
		{"Equal To By Definition", "≝"},
		{"Measured By", "≞"},
		{"Questioned Equal To", "≟"},
		{"Not Equal To", "≠"},
		{"Identical To", "≡"},
		{"Not Identical To", "≢"},
		{"Strictly Equivalent To", "≣"},
		{"Less Than Or Equal To", "≤"},
		{"Greater Than Or Equal To", "≥"},
		{"Less Than Over Equal To", "≦"},
		{"Greater Than Over Equal To", "≧"},
		{"Less Than But Not Equal To", "≨"},
		{"Greater Than But Not Equal To", "≩"},
		{"Much Less Than", "≪"},
		{"Much Greater Than", "≫"},
		{"Between", "≬"},
		{"Not Equivalent To", "≭"},
		{"Not Less Than", "≮"},
		{"Not Greater Than", "≯"},
		{"Neither Less Than Nor Equal To", "≰"},
		{"Neither Greater Than Nor Equal To", "≱"},
		{"Less Than Or Equivalent To", "≲"},
		{"Greater Than Or Equivalent To", "≳"},
		{"Neither Less Than Nor Equivalent To", "≴"},
		{"Neither Greater Than Nor Equivalent To", "≵"},
		{"Less Than Or Greater Than", "≶"},
		{"Greater Than Or Less Than", "≷"},
		{"Neither Less Than Nor Greater Than", "≸"},
		{"Neither Greater Than Nor Less Than", "≹"},
		{"Precedes", "≺"},
		{"Succeeds", "≻"},
		{"Precedes Or Equal To", "≼"},
		{"Succeeds Or Equal To", "≽"},
		{"Precedes Or Equivalent To", "≾"},
		{"Succeeds Or Equivalent To", "≿"},
		{"Does Not Precede", "⊀"},
		{"Does Not Succeed", "⊁"},
		{"Subset Of", "⊂"},
		{"Superset Of", "⊃"},
		{"Not A Subset Of", "⊄"},
		{"Not A Superset Of", "⊅"},
		{"Subset Of Or Equal To", "⊆"},
		{"Superset Of Or Equal To", "⊇"},
		{"Neither A Subset Of Nor Equal To", "⊈"},
		{"Neither A Superset Of Nor Equal To", "⊉"},
		{"Subset Of With Not Equal To", "⊊"},
		{"Superset Of With Not Equal To", "⊋"},
		{"Multiset", "⊌"},
		{"Multiset Multiplication", "⊍"},
		{"Multiset Union", "⊎"},
		{"Square Image Of", "⊏"},
		{"Square Original Of", "⊐"},
		{"Square Image Of Or Equal To", "⊑"},
		{"Square Original Of Or Equal To", "⊒"},
		{"Square Cap", "⊓"},
		{"Square Cup", "⊔"},
		{"Circled Plus", "⊕"},
		{"Circled Minus", "⊖"},
		{"Circled Times", "⊗"},
		{"Circled Division Slash", "⊘"},
		{"Circled Dot Operator", "⊙"},
		{"Circled Ring Operator", "⊚"},
		{"Circled Asterisk Operator", "⊛"},
		{"Circled Equals", "⊜"},
		{"Circled Dash", "⊝"},
		{"Squared Plus", "⊞"},
		{"Squared Minus", "⊟"},
		{"Squared Times", "⊠"},
		{"Squared Dot Operator", "⊡"},
		{"Right Tack", "⊢"},
		{"Left Tack", "⊣"},
		{"Down Tack", "⊤"},
		{"Up Tack", "⊥"},
		{"Assertion", "⊦"},
		{"Models", "⊧"},
		{"True", "⊨"},
		{"Forces", "⊩"},
		{"Triple Vertical Bar Right Turnstile", "⊪"},
		{"Double Vertical Bar Double Right Turnstile", "⊫"},
		{"Does Not Prove", "⊬"},
		{"Not True", "⊭"},
		{"Does Not Force", "⊮"},
		{"Negated Double Vertical Bar Double Right Turnstile", "⊯"},
		{"Precedes Under Relation", "⊰"},
		{"Succeeds Under Relation", "⊱"},
		{"Normal Subgroup Of", "⊲"},
		{"Contains As Normal Subgroup", "⊳"},
		{"Normal Subgroup Of Or Equal To", "⊴"},
		{"Contains As Normal Subgroup Or Equal To", "⊵"},
		{"Original Of", "⊶"},
		{"Image Of", "⊷"},
		{"Multimap", "⊸"},
		{"Hermitian Conjugate Matrix", "⊹"},
		{"Intercalate", "⊺"},
		{"Xor", "⊻"},
		{"Nand", "⊼"},
		{"Nor", "⊽"},
		{"Right Angle With Arc", "⊾"},
		{"Right Triangle", "⊿"},
		{"N Ary Logical And", "⋀"},
		{"N Ary Logical Or", "⋁"},
		{"N Ary Intersection", "⋂"},
		{"N Ary Union", "⋃"},
		{"Diamond Operator", "⋄"},
		{"Dot Operator", "⋅"},
		{"Star Operator", "⋆"},
		{"Division Times", "⋇"},
		{"Bowtie", "⋈"},
		{"Left Normal Factor Semidirect Product", "⋉"},
		{"Right Normal Factor Semidirect Product", "⋊"},
		{"Left Semidirect Product", "⋋"},
		{"Right Semidirect Product", "⋌"},
		{"Reversed Tilde Equals", "⋍"},
		{"Curly Logical Or", "⋎"},
		{"Curly Logical And", "⋏"},
		{"Double Subset", "⋐"},
		{"Double Superset", "⋑"},
		{"Double Intersection", "⋒"},
		{"Double Union", "⋓"},
		{"Pitchfork", "⋔"},
		{"Equal And Parallel To", "⋕"},
		{"Less Than With Dot", "⋖"},
		{"Greater Than With Dot", "⋗"},
		{"Very Much Less Than", "⋘"},
		{"Very Much Greater Than", "⋙"},
		{"Less Than Equal To Or Greater Than", "⋚"},
		{"Greater Than Equal To Or Less Than", "⋛"},
		{"Equal To Or Less Than", "⋜"},
		{"Equal To Or Greater Than", "⋝"},
		{"Equal To Or Precedes", "⋞"},
		{"Equal To Or Succeeds", "⋟"},
		{"Does Not Precede Or Equal", "⋠"},
		{"Does Not Succeed Or Equal", "⋡"},
		{"Not Square Image Of Or Equal To", "⋢"},
		{"Not Square Original Of Or Equal To", "⋣"},
		{"Square Image Of Or Not Equal To", "⋤"},
		{"Square Original Of Or Not Equal To", "⋥"},
		{"Less Than But Not Equivalent To", "⋦"},
		{"Greater Than But Not Equivalent To", "⋧"},
		{"Precedes But Not Equivalent To", "⋨"},
		{"Succeeds But Not Equivalent To", "⋩"},
		{"Not Normal Subgroup Of", "⋪"},
		{"Does Not Contain As Normal Subgroup", "⋫"},
		{"Not Normal Subgroup Of Or Equal To", "⋬"},
		{"Does Not Contain As Normal Subgroup Or Equal", "⋭"},
		{"Vertical Ellipsis", "⋮"},
		{"Midline Horizontal Ellipsis", "⋯"},
		{"Up Right Diagonal Ellipsis", "⋰"},
		{"Down Right Diagonal Ellipsis", "⋱"},
		{"Element Of With Long Horizontal Stroke", "⋲"},
		{"Element Of With Vertical Bar At End Of Horizontal Stroke", "⋳"},
		{"Small Element Of With Vertical Bar At End Of Horizontal Stroke", "⋴"},
		{"Element Of With Dot Above", "⋵"},
		{"Element Of With Overbar", "⋶"},
		{"Small Element Of With Overbar", "⋷"},
		{"Element Of With Underbar", "⋸"},
		{"Element Of With Two Horizontal Strokes", "⋹"},
		{"Contains With Long Horizontal Stroke", "⋺"},
		{"Contains With Vertical Bar At End Of Horizontal Stroke", "⋻"},
		{"Small Contains With Vertical Bar At End Of Horizontal Stroke", "⋼"},
		{"Contains With Overbar", "⋽"},
		{"Small Contains With Overbar", "⋾"},
		{"Z Notation Bag Membership", "⋿"},
		{"Multiplication X", "✕"},
		{"Heavy Multiplication X", "✖"},
		{"Heavy Greek Cross", "✚"},
	}
	i = v.NewItem("Math")
	i.SetIcon(iconPath("math", "Surface Integral"))
	i.SetActionRunsInBackground(false)
	i.SetActionReturnsItems(true)
	i.SetRun(func(c *Context) Items {
		items := NewItems()
		for _, row := range chars {
			i := NewItem(row[0])
			i.SetIcon(iconPath("math", row[0]))
			i.Run("showChar", row[0], row[1])
			i.SetAction("unisym")
			i.SetActionReturnsItems(true)
			i.SetActionRunsInBackground(false)
			items.Add(i)
		}
		return *items
	})
}
