package main

func init() {
	chars["numerals"] = [][2]string{
		{"Digit One Full Stop", "⒈"},
		{"Digit Two Full Stop", "⒉"},
		{"Digit Three Full Stop", "⒊"},
		{"Digit Four Full Stop", "⒋"},
		{"Digit Five Full Stop", "⒌"},
		{"Digit Six Full Stop", "⒍"},
		{"Digit Seven Full Stop", "⒎"},
		{"Digit Eight Full Stop", "⒏"},
		{"Digit Nine Full Stop", "⒐"},
		{"Number Ten Full Stop", "⒑"},
		{"Number Eleven Full Stop", "⒒"},
		{"Number Twelve Full Stop", "⒓"},
		{"Number Thirteen Full Stop", "⒔"},
		{"Number Fourteen Full Stop", "⒕"},
		{"Number Fifteen Full Stop", "⒖"},
		{"Number Sixteen Full Stop", "⒗"},
		{"Number Seventeen Full Stop", "⒘"},
		{"Number Eighteen Full Stop", "⒙"},
		{"Number Nineteen Full Stop", "⒚"},
		{"Number Twenty Full Stop", "⒛"},
		{"Circled Digit Zero", "⓪"},
		{"Circled Digit One", "①"},
		{"Circled Digit Two", "②"},
		{"Circled Digit Three", "③"},
		{"Circled Digit Four", "④"},
		{"Circled Digit Five", "⑤"},
		{"Circled Digit Six", "⑥"},
		{"Circled Digit Seven", "⑦"},
		{"Circled Digit Eight", "⑧"},
		{"Circled Digit Nine", "⑨"},
		{"Circled Number Ten", "⑩"},
		{"Dingbat Circled Sans Serif Digit One", "➀"},
		{"Dingbat Circled Sans Serif Digit Two", "➁"},
		{"Dingbat Circled Sans Serif Digit Three", "➂"},
		{"Dingbat Circled Sans Serif Digit Four", "➃"},
		{"Dingbat Circled Sans Serif Digit Five", "➄"},
		{"Dingbat Circled Sans Serif Digit Six", "➅"},
		{"Dingbat Circled Sans Serif Digit Seven", "➆"},
		{"Dingbat Circled Sans Serif Digit Eight", "➇"},
		{"Dingbat Circled Sans Serif Digit Nine", "➈"},
		{"Dingbat Circled Sans Serif Number Ten", "➉"},
		{"Circled Number Eleven", "⑪"},
		{"Circled Number Twelve", "⑫"},
		{"Circled Number Thirteen", "⑬"},
		{"Circled Number Fourteen", "⑭"},
		{"Circled Number Fifteen", "⑮"},
		{"Circled Number Sixteen", "⑯"},
		{"Circled Number Seventeen", "⑰"},
		{"Circled Number Eighteen", "⑱"},
		{"Circled Number Nineteen", "⑲"},
		{"Circled Number Twenty", "⑳"},
		{"Negative Circled Digit Zero", "⓿"},
		{"Dingbat Negative Circled Digit One", "❶"},
		{"Dingbat Negative Circled Digit Two", "❷"},
		{"Dingbat Negative Circled Digit Three", "❸"},
		{"Dingbat Negative Circled Digit Four", "❹"},
		{"Dingbat Negative Circled Digit Five", "❺"},
		{"Dingbat Negative Circled Digit Six", "❻"},
		{"Dingbat Negative Circled Digit Seven", "❼"},
		{"Dingbat Negative Circled Digit Eight", "❽"},
		{"Dingbat Negative Circled Digit Nine", "❾"},
		{"Dingbat Negative Circled Number Ten", "❿"},
		{"Dingbat Negative Circled Sans Serif Digit One", "➊"},
		{"Dingbat Negative Circled Sans Serif Digit Two", "➋"},
		{"Dingbat Negative Circled Sans Serif Digit Three", "➌"},
		{"Dingbat Negative Circled Sans Serif Digit Four", "➍"},
		{"Dingbat Negative Circled Sans Serif Digit Five", "➎"},
		{"Dingbat Negative Circled Sans Serif Digit Six", "➏"},
		{"Dingbat Negative Circled Sans Serif Digit Seven", "➐"},
		{"Dingbat Negative Circled Sans Serif Digit Eight", "➑"},
		{"Dingbat Negative Circled Sans Serif Digit Nine", "➒"},
		{"Dingbat Negative Circled Sans Serif Number Ten", "➓"},
		{"Negative Circled Number Eleven", "⓫"},
		{"Negative Circled Number Twelve", "⓬"},
		{"Negative Circled Number Thirteen", "⓭"},
		{"Negative Circled Number Fourteen", "⓮"},
		{"Negative Circled Number Fifteen", "⓯"},
		{"Negative Circled Number Sixteen", "⓰"},
		{"Negative Circled Number Seventeen", "⓱"},
		{"Negative Circled Number Eighteen", "⓲"},
		{"Negative Circled Number Nineteen", "⓳"},
		{"Negative Circled Number Twenty", "⓴"},
		{"Parenthesized Digit One", "⑴"},
		{"Parenthesized Digit Two", "⑵"},
		{"Parenthesized Digit Three", "⑶"},
		{"Parenthesized Digit Four", "⑷"},
		{"Parenthesized Digit Five", "⑸"},
		{"Parenthesized Digit Six", "⑹"},
		{"Parenthesized Digit Seven", "⑺"},
		{"Parenthesized Digit Eight", "⑻"},
		{"Parenthesized Digit Nine", "⑼"},
		{"Parenthesized Number Ten", "⑽"},
		{"Parenthesized Number Eleven", "⑾"},
		{"Parenthesized Number Twelve", "⑿"},
		{"Parenthesized Number Thirteen", "⒀"},
		{"Parenthesized Number Fourteen", "⒁"},
		{"Parenthesized Number Fifteen", "⒂"},
		{"Parenthesized Number Sixteen", "⒃"},
		{"Parenthesized Number Seventeen", "⒄"},
		{"Parenthesized Number Eighteen", "⒅"},
		{"Parenthesized Number Nineteen", "⒆"},
		{"Parenthesized Number Twenty", "⒇"},
		{"Superscript One", "¹"},
		{"Superscript Two", "²"},
		{"Superscript Three", "³"},
		{"Vulgar Fraction Zero Thirds", "↉"},
		{"Vulgar Fraction One Half", "½"},
		{"Vulgar Fraction One Third", "⅓"},
		{"Vulgar Fraction One Quarter", "¼"},
		{"Vulgar Fraction One Fifth", "⅕"},
		{"Vulgar Fraction One Sixth", "⅙"},
		{"Vulgar Fraction One Seventh", "⅐"},
		{"Vulgar Fraction One Eighth", "⅛"},
		{"Vulgar Fraction One Ninth", "⅑"},
		{"Vulgar Fraction One Tenth", "⅒"},
		{"Vulgar Fraction Two Thirds", "⅔"},
		{"Vulgar Fraction Two Fifths", "⅖"},
		{"Vulgar Fraction Three Quarters", "¾"},
		{"Vulgar Fraction Three Fifths", "⅗"},
		{"Vulgar Fraction Three Eighths", "⅜"},
		{"Vulgar Fraction Four Fifths", "⅘"},
		{"Vulgar Fraction Five Sixths", "⅚"},
		{"Vulgar Fraction Five Eighths", "⅝"},
		{"Vulgar Fraction Seven Eighths", "⅞"},
		{"Double Circled Digit One", "⓵"},
		{"Double Circled Digit Two", "⓶"},
		{"Double Circled Digit Three", "⓷"},
		{"Double Circled Digit Four", "⓸"},
		{"Double Circled Digit Five", "⓹"},
		{"Double Circled Digit Six", "⓺"},
		{"Double Circled Digit Seven", "⓻"},
		{"Double Circled Digit Eight", "⓼"},
		{"Double Circled Digit Nine", "⓽"},
		{"Double Circled Number Ten", "⓾"},
	}
}
