package main

import . "github.com/nbjahan/go-launchbar"

func addPunctuations() {
	var i *Item
	v := pb.GetView("main")

	chars := [][2]string{
		{"Heavy Double Turned Comma Quotation Mark Ornament", "❝"},
		{"Heavy Double Comma Quotation Mark Ornament", "❞"},
		{"Heavy Single Turned Comma Quotation Mark Ornament", "❛"},
		{"Heavy Single Comma Quotation Mark Ornament", "❜"},
		{"Left Single Quotation Mark", "‘"},
		{"Right Single Quotation Mark", "’"},
		{"Single High Reversed 9 Quotation Mark", "‛"},
		{"Single Low 9 Quotation Mark", "‚"},
		{"Left Double Quotation Mark", "“"},
		{"Right Double Quotation Mark", "”"},
		{"Double Low 9 Quotation Mark", "„"},
		{"Double High Reversed 9 Quotation Mark", "‟"},
		{"Left Pointing Double Angle Quotation Mark", "«"},
		{"Right Pointing Double Angle Quotation Mark", "»"},
		{"Single Left Pointing Angle Quotation Mark", "‹"},
		{"Single Right Pointing Angle Quotation Mark", "›"},
		{"Latin Capital Letter Saltillo", "Ꞌ"},
		{"Quotation Mark", "&"},
		{"Less Than Sign", "&"},
		{"Greater Than Sign", "&"},
		{"Commercial At", "@"},
		{"Multiplication Sign", "×"},
		{"Hyphenation Point", "‧"},
		{"Diaeresis", "¨"},
		{"One Dot Leader", "․"},
		{"Modifier Letter Colon", "꞉"},
		{"Colon", ":"},
		{"Two Dot Punctuation", "⁚"},
		{"Tricolon", "⁝"},
		{"Vertical Four Dots", "⁞"},
		{"Two Dot Leader", "‥"},
		{"Horizontal Ellipsis", "…"},
		{"Three Dot Punctuation", "⁖"},
		{"Two Dots Over One Dot Punctuation", "⸪"},
		{"Squared Four Dot Punctuation", "⸬"},
		{"One Dot Over Two Dots Punctuation", "⸫"},
		{"Five Dot Mark", "⸭"},
		{"Four Dot Mark", "⁛"},
		{"Four Dot Punctuation", "⁘"},
		{"Five Dot Punctuation", "⁙"},
		{"Reversed Semicolon", "⁏"},
		{"Semicolon", ";"},
		{"Z Notation Type Colon", "⦂"},
		{"Hyphen Bullet", "⁃"},
		{"Hyphen", "‐"},
		{"Non Breaking Hyphen", "‑"},
		{"Figure Dash", "‒"},
		{"Hyphen Minus", "-"},
		{"En Dash", "–"},
		{"Horizontal Line Extension", "⎯"},
		{"Em Dash", "—"},
		{"Horizontal Bar", "―"},
		{"Low Line", "_"},
		{"Tilde", "~"},
		{"Swung Dash", "⁓"},
		{"Tilde With Ring Above", "⸛"},
		{"Tilde With Dot Above", "⸞"},
		{"Tilde With Dot Below", "⸟"},
		{"Vertical Tilde", "ⸯ"},
		{"Not Sign", "¬"},
		{"Solidus", "/"},
		{"Reverse Solidus", "\\"},
		{"Fraction Slash", "⁄"},
		{"Vertical Line", "|"},
		{"Left Parenthesis Extension", "⎜"},
		{"Broken Bar", "¦"},
		{"Double Vertical Line", "‖"},
		{"Double Low Line", "‗"},
		{"Dagger", "†"},
		{"Double Dagger", "‡"},
		{"Middle Dot", "·"},
		{"Bullet", "•"},
		{"Ring Point", "⸰"},
		{"Degree Sign", "°"},
		{"Triangular Bullet", "‣"},
		{"Commercial Minus Sign", "⁒"},
		{"Percent Sign", "%"},
		{"Per Mille Sign", "‰"},
		{"Per Ten Thousand Sign", "‱"},
		{"Ampersand", "&"},
		{"Turned Ampersand", "⅋"},
		{"Section Sign", "§"},
		{"Division Sign", "÷"},
		{"Plus Sign", "+"},
		{"Plus Minus Sign", "±"},
		{"Equals Sign", "="},
		{"Modifier Letter Short Equals Sign", "꞊"},
		{"Prime", "′"},
		{"Double Prime", "″"},
		{"Triple Prime", "‴"},
		{"Quadruple Prime", "⁗"},
		{"Reversed Prime", "‵"},
		{"Reversed Double Prime", "‶"},
		{"Reversed Triple Prime", "‷"},
		{"Caret", "‸"},
		{"Asterisk", "*"},
		{"Two Asterisks Aligned Vertically", "⁑"},
		{"Low Asterisk", "⁎"},
		{"Flower Punctuation Mark", "⁕"},
		{"Reference Mark", "※"},
		{"Dotted Cross", "⁜"},
		{"Asterism", "⁂"},
		{"Exclamation Mark", "!"},
		{"Double Exclamation Mark", "‼"},
		{"Inverted Exclamation Mark", "¡"},
		{"Question Mark", "?"},
		{"Inverted Question Mark", "¿"},
		{"Reversed Question Mark", "⸮"},
		{"Double Question Mark", "⁇"},
		{"Exclamation Question Mark", "⁉"},
		{"Question Exclamation Mark", "⁈"},
		{"Interrobang", "‽"},
		{"Inverted Interrobang", "⸘"},
		{"Vulgar Fraction One Quarter", "¼"},
		{"Vulgar Fraction One Half", "½"},
		{"Vulgar Fraction Three Quarters", "¾"},
		{"Superscript Two", "²"},
		{"Superscript Three", "³"},
		{"Copyright Sign", "©"},
		{"Registered Sign", "®"},
		{"Trade Mark Sign", "™"},
		{"Service Mark", "℠"},
		{"Facsimile Sign", "℻"},
		{"Care Of", "℅"},
		{"Addressed To The Subject", "℁"},
		{"Aktieselskab", "⅍"},
		{"Centre Line Symbol", "℄"},
		{"Pilcrow Sign", "¶"},
		{"Reversed Pilcrow Sign", "⁋"},
		{"Curved Stem Paragraph Sign Ornament", "❡"},
		{"Black Leftwards Bullet", "⁌"},
		{"Black Rightwards Bullet", "⁍"},
		{"Dotted Right Pointing Angle", "⸖"},
		{"Double Oblique Hyphen", "⸗"},
		{"Hyphen With Diaeresis", "⸚"},
		{"Dotted Obelos", "⸓"},
		{"Left Parenthesis", "("},
		{"Right Parenthesis", ")"},
		{"Left Square Bracket", "["},
		{"Right Square Bracket", "]"},
		{"Left Curly Bracket", "{"},
		{"Right Curly Bracket", "}"},
		{"Left Double Parenthesis", "⸨"},
		{"Right Double Parenthesis", "⸩"},
		{"Medium Left Parenthesis Ornament", "❨"},
		{"Medium Right Parenthesis Ornament", "❩"},
		{"Medium Flattened Left Parenthesis Ornament", "❪"},
		{"Medium Flattened Right Parenthesis Ornament", "❫"},
		{"Left Sideways U Bracket", "⸦"},
		{"Right Sideways U Bracket", "⸧"},
		{"Medium Left Pointing Angle Bracket Ornament", "❬"},
		{"Medium Right Pointing Angle Bracket Ornament", "❭"},
		{"Heavy Left Pointing Angle Quotation Mark Ornament", "❮"},
		{"Heavy Right Pointing Angle Quotation Mark Ornament", "❯"},
		{"Heavy Left Pointing Angle Bracket Ornament", "❰"},
		{"Heavy Right Pointing Angle Bracket Ornament", "❱"},
		{"Medium Left Curly Bracket Ornament", "❴"},
		{"Medium Right Curly Bracket Ornament", "❵"},
		{"Light Left Tortoise Shell Bracket Ornament", "❲"},
		{"Light Right Tortoise Shell Bracket Ornament", "❳"},
		{"Left Black Tortoise Shell Bracket", "⦗"},
		{"Right Black Tortoise Shell Bracket", "⦘"},
		{"Left Square Bracket With Quill", "⁅"},
		{"Right Square Bracket With Quill", "⁆"},
		{"Left Pointing Angle Bracket", "〈"},
		{"Right Pointing Angle Bracket", "〉"},
		{"Top Parenthesis", "⏜"},
		{"Bottom Parenthesis", "⏝"},
		{"Top Curly Bracket", "⏞"},
		{"Bottom Curly Bracket", "⏟"},
		{"Right Vertical Bar With Quill", "⸡"},
		{"Left Vertical Bar With Quill", "⸠"},
		{"Top Left Half Bracket", "⸢"},
		{"Top Right Half Bracket", "⸣"},
		{"Bottom Left Half Bracket", "⸤"},
		{"Bottom Right Half Bracket", "⸥"},
		{"Left Square Bracket Upper Corner", "⎡"},
		{"Right Square Bracket Upper Corner", "⎤"},
		{"Left Square Bracket Lower Corner", "⎣"},
		{"Right Square Bracket Lower Corner", "⎦"},
		{"Left Curly Bracket Middle Piece", "⎨"},
		{"Right Curly Bracket Middle Piece", "⎬"},
		{"Top Half Integral", "⌠"},
		{"Bottom Half Integral", "⌡"},
		{"Left Parenthesis Upper Hook", "⎛"},
		{"Right Parenthesis Lower Hook", "⎠"},
		{"Left Parenthesis Lower Hook", "⎝"},
		{"Right Parenthesis Upper Hook", "⎞"},
		{"Character Tie", "⁀"},
		{"Inverted Undertie", "⁔"},
		{"Undertie", "‿"},
		{"Close Up", "⁐"},
		{"Overline", "‾"},
		{"Right Parenthesis Extension", "⎟"},
		{"Left Square Bracket Extension", "⎢"},
		{"Right Square Bracket Extension", "⎥"},
		{"Curly Bracket Extension", "⎪"},
		{"Latin Small Letter Turned L", "ꞁ"},
		{"Integral Extension", "⎮"},
		{"Left Curly Bracket Upper Hook", "⎧"},
		{"Right Curly Bracket Upper Hook", "⎫"},
		{"Left Curly Bracket Lower Hook", "⎩"},
		{"Right Curly Bracket Lower Hook", "⎭"},
		{"Upper Left Or Lower Right Curly Bracket Section", "⎰"},
		{"Upper Right Or Lower Left Curly Bracket Section", "⎱"},
		{"Apostrophe", "'"},
	}
	i = v.NewItem("Punctuations")
	i.SetIcon(iconPath("punctuations", "Heavy Double Comma Quotation Mark Ornament"))
	i.SetActionRunsInBackground(false)
	i.SetActionReturnsItems(true)
	i.SetRun(func(c *Context) Items {
		items := NewItems()
		for _, row := range chars {
			i := NewItem(row[0])
			i.SetIcon(iconPath("punctuations", row[0]))
			i.Run("showChar", row[0], row[1])
			i.SetAction("unisym")
			i.SetActionReturnsItems(true)
			i.SetActionRunsInBackground(false)
			items.Add(i)
		}
		return *items
	})
}
